export const actionTypes = {

  MAINMENU_START_FETCHING: 'MAINMENU_START_FETCHING',
  MAINMENU_FETCHED: 'MAINMENU_FETCHED',
  MEINMENU_FETCH_ERROR: 'MEINMENU_FETCH_ERROR',

  IMAGE_START_FETCHING: 'IMAGE_START_FETCHING',
  IMAGE_FETCHED: 'IMAGE_FETCHED',
  IMAGE_FETCH_ERROR: 'IMAGE_FETCH_ERROR',


}