export const actionTypes = {

  MAIN_NAV_START_FETCHING: 'MAIN_NAV_START_FETCHING',
  MAIN_NAV_FETCHED: 'MAIN_NAV_FETCHED',
  MAIN_NAV_FETCH_ERROR: 'MAIN_NAV_FETCH_ERROR',

  BLOG_START_FETCHING: 'BLOG_START_FETCHING',
  BLOG_FETCHED: 'BLOG_FETCHED',
  BLOG_FETCH_ERROR: 'BLOG_FETCH_ERROR',

  TAXONOMY_START_FETCHING: 'TAXONOMY_START_FETCHING',
  TAXONOMY_FETCHED: 'TAXONOMY_FETCHED',
  TAXONOMY_FETCH_ERROR: 'TAXONOMY_FETCH_ERROR',

  SELECTED_YEAR_MONTH: 'SELECTED_YEAR_MONTH'

}